# Change these first
owner: schubi-lab # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: Schubi-Lab
    url: https://schubi-lab.de
 # - name: Blog
 #   url: https://blog.schubi-lab.de
 # - name: Authelia
 #   url: https://auth.schubi-lab.de


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: https://schubilab.github.io/up/
  baseUrl: /up
  theme: night
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Up
  introTitle: "**Hello World :)**"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: Visit my [website](https://schubi-lab.de)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
